name: Devops Demo

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Login to dockerhub
        run: echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: build docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/devops-demo .

      - name: publish to docker hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}